# Generated by Django 5.0.5 on 2024-05-07 17:06

import django.core.validators
import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cat', unique=True)),
                ('title', models.CharField(default='Biomedical', max_length=255)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(default='portifolio.jpg', upload_to='portifolio_images')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='doc')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='ven', unique=True)),
                ('title', models.CharField(default='Vendor', max_length=100)),
                ('image', models.ImageField(default='vendor.jpg', upload_to='vendor-images')),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(default='10 Kinondoni Dar es Salaam', max_length=100)),
                ('contact', models.CharField(default='+255 000 000 000', max_length=100)),
                ('chat_resp_time', models.CharField(default=100, max_length=100)),
                ('shipping_on_time', models.CharField(default=100, max_length=100)),
                ('authentic_rating', models.CharField(default=100, max_length=100)),
                ('days_return', models.CharField(default=100, max_length=100)),
                ('warranty_period', models.CharField(default=100, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PortifolioImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='portifolio.jpg', upload_to='Portifolio-images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portifolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.portifolio')),
            ],
            options={
                'verbose_name_plural': 'Portifolio Images',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='', unique=True)),
                ('title', models.CharField(default='Product', max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('image', models.ImageField(default='avatar.png', upload_to='product_images')),
                ('description', models.TextField(blank=True, default='This is a product', null=True)),
                ('price', models.DecimalField(decimal_places=2, default='10000.00', max_digits=999999999999, validators=[django.core.validators.MinValueValidator(100)])),
                ('old_price', models.DecimalField(decimal_places=2, default='20000.00', max_digits=999999999999, validators=[django.core.validators.MinValueValidator(100)])),
                ('specifications', models.TextField(blank=True, null=True)),
                ('product_status', models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('published', 'Published')], default='in_review', max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=10, prefix='sku', unique=True)),
                ('inventory', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.collection')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='featured_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.product'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to='product-images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
