# Generated by Django 5.0.5 on 2024-05-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='20000.00', max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='10000.00', max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.CharField(blank=True, default='Specifications', max_length=255, null=True),
        ),
    ]
