# Generated by Django 5.0.5 on 2024-05-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_product_old_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='file',
            field=models.FileField(default='priceList.txt', upload_to='doc'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='title',
            field=models.CharField(default='Product Price List', max_length=255),
        ),
    ]
