# Generated by Django 5.0.4 on 2024-04-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_product_slug_alter_product_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
