# Generated by Django 5.0.4 on 2024-04-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_product_image_alter_collection_featured_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='product_images'),
        ),
    ]
