# Generated by Django 5.0.4 on 2024-04-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(default='portifolio.jpg', upload_to='portifolio_images')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
