# Generated by Django 5.0.4 on 2024-04-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
